# Copyright (C) 2017 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

"""
Add maintenance table

Create Date: 2017-08-22 18:08:33.976627
"""
# disable Invalid constant name pylint warning for mandatory Alembic variables.
# pylint: disable=invalid-name

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58b215ec5cd3'
down_revision = '2ada007df3ee'


def upgrade():
    """Upgrade database schema and/or data, creating a new revision."""
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_db_migrate', sa.Boolean(), nullable=False),
    sa.Column('run_revision_refresh', sa.Boolean(), nullable=False),
    sa.Column('run_reindex', sa.Boolean(), nullable=False),
    sa.Column('run_computed_attribute', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    """Downgrade database schema and/or data back to the previous revision."""
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenances')
    ### end Alembic commands ###
